spring:
  datasource:
    url: ${DB_URL:jdbc:h2:file:./data/policies;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE}
    username: ${DB_USER:sa}
    password: ${DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: health,info
springdoc:
  swagger-ui:
    path: /swagger-ui.html
